In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
nfl_cell = pd.read_clipboard()

In [8]:
nfl_cell['Team'][2]

'New England Patriots'

In [9]:
nfl_cell

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season,Division
0,1,Dallas Cowboys,914,520,388,6,0.572,1960,NFC East
1,2,Green Bay Packers,"1,368",756,574,38,0.567,1921,NFC North
2,3,New England Patriots,916,512,395,9,0.564,1960,AFC East
3,4,Chicago Bears,"1,402",769,591,42,0.563,1920,NFC North
4,5,Baltimore Ravens,384,214,169,1,0.559,1996,AFC North
5,6,Miami Dolphins,832,457,371,4,0.552,1966,AFC East
6,7,Minnesota Vikings,902,488,403,11,0.547,1961,NFC North
7,8,San Francisco 49ers,"1,034",545,475,14,0.534,1950,NFC West
8,9,New York Giants,"1,337",696,608,33,0.533,1925,NFC East
9,10,Denver Broncos,916,483,423,10,0.533,1960,AFC West
10,11,Kansas City Chiefs,916,481,423,12,0.532,1960,AFC West
11,12,Pittsburgh Steelers,"1,224",636,566,22,0.529,1933,AFC North
12,13,Indianapolis Colts,998,523,468,7,0.528,1953,AFC South
13,14,Las Vegas Raiders,916,473,432,11,0.522,1960,AFC West
14,15,Seattle Seahawks,692,355,336,1,0.514,1976,NFC West
15,16,Los Angeles Rams,"1,167",577,569,21,0.503,1937,NFC West
16,17,Washington Redskins,"1,234",603,603,28,0.500,1932,NFC East
17,18,Los Angeles Chargers,916,452,453,11,0.499,1960,AFC West
18,19,Philadelphia Eagles,"1,220",586,608,26,0.491,1933,NFC East
19,20,Carolina Panthers,400,195,204,1,0.489,1995,NFC South
20,21,Cleveland Browns,986,475,500,11,0.487,1950,AFC North
21,22,Tennessee Titans,916,440,470,6,0.484,1960,AFC South
22,23,Buffalo Bills,916,425,483,8,0.468,1960,AFC East
23,24,New Orleans Saints,818,375,438,5,0.461,1967,NFC South
24,25,Detroit Lions,"1,265",562,670,33,0.457,1930,NFC North
25,26,Houston Texans,288,131,157,0,0.455,2002,AFC South
26,27,New York Jets,916,408,500,8,0.450,1960,AFC East
27,28,Cincinnati Bengals,804,359,441,4,0.449,1968,AFC North
28,29,Atlanta Falcons,832,365,461,6,0.448,1966,NFC South
29,30,Jacksonville Jaguars,400,176,224,0,0.440,1995,AFC South
30,31,Arizona Cardinals,"1,362",558,763,41,0.425,1920,NFC West
31,32,Tampa Bay Buccaneers,692,267,424,1,0.387,1976,NFC South

In [13]:
del nfl_cell['Division']

In [14]:
nfl_cell

,Rank,Team,GP,Won,Lost,Tied,Pct.,First NFL Season
0,1,Dallas Cowboys,914,520,388,6,0.572,1960
1,2,Green Bay Packers,"1,368",756,574,38,0.567,1921
2,3,New England Patriots,916,512,395,9,0.564,1960
3,4,Chicago Bears,"1,402",769,591,42,0.563,1920
4,5,Baltimore Ravens,384,214,169,1,0.559,1996
5,6,Miami Dolphins,832,457,371,4,0.552,1966
6,7,Minnesota Vikings,902,488,403,11,0.547,1961
7,8,San Francisco 49ers,"1,034",545,475,14,0.534,1950
8,9,New York Giants,"1,337",696,608,33,0.533,1925
9,10,Denver Broncos,916,483,423,10,0.533,1960
10,11,Kansas City Chiefs,916,481,423,12,0.532,1960
11,12,Pittsburgh Steelers,"1,224",636,566,22,0.529,1933
12,13,Indianapolis Colts,998,523,468,7,0.528,1953
13,14,Las Vegas Raiders,916,473,432,11,0.522,1960
14,15,Seattle Seahawks,692,355,336,1,0.514,1976
15,16,Los Angeles Rams,"1,167",577,569,21,0.503,1937
16,17,Washington Redskins,"1,234",603,603,28,0.500,1932
17,18,Los Angeles Chargers,916,452,453,11,0.499,1960
18,19,Philadelphia Eagles,"1,220",586,608,26,0.491,1933
19,20,Carolina Panthers,400,195,204,1,0.489,1995
20,21,Cleveland Browns,986,475,500,11,0.487,1950
21,22,Tennessee Titans,916,440,470,6,0.484,1960
22,23,Buffalo Bills,916,425,483,8,0.468,1960
23,24,New Orleans Saints,818,375,438,5,0.461,1967
24,25,Detroit Lions,"1,265",562,670,33,0.457,1930
25,26,Houston Texans,288,131,157,0,0.455,2002
26,27,New York Jets,916,408,500,8,0.450,1960
27,28,Cincinnati Bengals,804,359,441,4,0.449,1968
28,29,Atlanta Falcons,832,365,461,6,0.448,1966
29,30,Jacksonville Jaguars,400,176,224,0,0.440,1995
30,31,Arizona Cardinals,"1,362",558,763,41,0.425,1920
31,32,Tampa Bay Buccaneers,692,267,424,1,0.387,1976